# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate croner

Name:           rust-croner
Version:        3.0.1
Release:        %autorelease
Summary:        Rust library designed for parsing and evaluating cron patterns

License:        MIT
URL:            https://crates.io/crates/croner
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * relax chrono-tz dependency from 0.10.4 to >=0.10,<0.13
# * drop criterion dependency
Patch:          croner-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fully-featured, lightweight, and efficient Rust library designed for
parsing and evaluating cron patterns.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
